"""
alert_system.py
───────────────
Sends email alerts when a DDoS attack is detected.

Setup:
    1. Set your Gmail address and app password below.
    2. Enable 2FA on Gmail and generate an App Password:
       https://myaccount.google.com/apppasswords

Usage:
    from alerts.alert_system import AlertSystem
    alert = AlertSystem()
    alert.send_alert(src_ip='10.0.0.99', attack_type='SYN Flood')
"""

import smtplib
import logging
import time
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

logger = logging.getLogger('AlertSystem')

# ── Configure these ───────────────────────────────────────────
SENDER_EMAIL    = 'your_email@gmail.com'       # ← Change this
SENDER_PASSWORD = 'your_app_password'          # ← Change this (Gmail App Password)
RECEIVER_EMAIL  = 'your_email@gmail.com'       # ← Where alerts are sent
SMTP_SERVER     = 'smtp.gmail.com'
SMTP_PORT       = 587

# Throttle: don't send more than 1 alert per IP per 5 minutes
ALERT_COOLDOWN_SEC = 300
# ─────────────────────────────────────────────────────────────


class AlertSystem:

    def __init__(self):
        self._last_alert = {}   # ip → timestamp

    def _can_alert(self, src_ip):
        """Return True if enough time has passed since last alert for this IP."""
        last = self._last_alert.get(src_ip, 0)
        return (time.time() - last) > ALERT_COOLDOWN_SEC

    def send_alert(self, src_ip, attack_type='DDoS', confidence=None, blocked=True):
        """
        Send an email alert about a detected DDoS attack.

        Parameters:
            src_ip      : attacker's IP address
            attack_type : type of attack detected (default 'DDoS')
            confidence  : model confidence score (float, optional)
            blocked     : whether the IP was automatically blocked
        """
        if not self._can_alert(src_ip):
            logger.debug(f"Alert suppressed for {src_ip} (cooldown active)")
            return

        timestamp  = time.strftime('%Y-%m-%d %H:%M:%S')
        status_msg = "✅ Automatically BLOCKED" if blocked else "⚠️  Manual action required"
        conf_str   = f"{confidence*100:.1f}%" if confidence else "N/A"

        subject = f"[ALERT] DDoS Attack Detected — {src_ip}"
        body    = f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 DDoS DETECTION ALERT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

 Timestamp   : {timestamp}
 Source IP   : {src_ip}
 Attack Type : {attack_type}
 Confidence  : {conf_str}
 Status      : {status_msg}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 This alert was generated by the Hybrid SVM-RF
 DDoS Detection Framework running on your SDN.
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
        """

        try:
            msg = MIMEMultipart()
            msg['From']    = SENDER_EMAIL
            msg['To']      = RECEIVER_EMAIL
            msg['Subject'] = subject
            msg.attach(MIMEText(body, 'plain'))

            with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
                server.ehlo()
                server.starttls()
                server.login(SENDER_EMAIL, SENDER_PASSWORD)
                server.sendmail(SENDER_EMAIL, RECEIVER_EMAIL, msg.as_string())

            self._last_alert[src_ip] = time.time()
            logger.info(f"[ALERT SENT] DDoS from {src_ip} → {RECEIVER_EMAIL}")

        except smtplib.SMTPAuthenticationError:
            logger.error(
                "Email authentication failed. "
                "Check SENDER_EMAIL and SENDER_PASSWORD in alert_system.py"
            )
        except Exception as e:
            logger.error(f"Failed to send alert: {e}")

    def log_attack(self, src_ip, attack_type='DDoS', confidence=None):
        """Log attack to console without sending email (useful for testing)."""
        timestamp = time.strftime('%Y-%m-%d %H:%M:%S')
        conf_str  = f"{confidence*100:.1f}%" if confidence else "N/A"
        print(
            f"\n{'='*50}\n"
            f"  [ATTACK DETECTED]\n"
            f"  Time       : {timestamp}\n"
            f"  Source IP  : {src_ip}\n"
            f"  Type       : {attack_type}\n"
            f"  Confidence : {conf_str}\n"
            f"{'='*50}"
        )


if __name__ == '__main__':
    print("Testing AlertSystem (console log only)...")
    alert = AlertSystem()
    alert.log_attack(src_ip='10.0.0.99', attack_type='SYN Flood', confidence=0.987)
    print("\nTo test email alerts, fill in SENDER_EMAIL and SENDER_PASSWORD,")
    print("then call: alert.send_alert(src_ip='10.0.0.99')")
